In [1]:
import PyPDF2 as pypdf
import re
import numpy as np
import csv
import pandas as pd

In [4]:
Saginaw_Chippewa_pdf = open("/Users/varshamadapoosi/Downloads/Saginaw Chippewa Tribal College.pdf", "rb")
Leech_Lake_pdf = open("/Users/varshamadapoosi/Downloads/Leech Lake Tribal College.pdf", "rb")
Lac_Courte_Oreilles_Ojibwa_pdf = open("/Users/varshamadapoosi/Downloads/Lac Courte Oreilles Ojibwa Community College  .pdf", "rb")
Aaniiih_Nakoda_pdf = open("/Users/varshamadapoosi/Downloads/Aaniiih Nakoda College.pdf", "rb")
Blackfeet_CC_pdf = open("/Users/varshamadapoosi/Downloads/Blackfeet Community College.pdf", "rb")
Southwest_Indian_polytechnic= open("/Users/varshamadapoosi/Downloads/SIPI 2017-2018 Catalog Final.pdf", "rb")
Keweenaw_Bay_Ojibwa_pdf = open("/Users/varshamadapoosi/Downloads/2018-2020-KBOCC-Catalog.pdf", "rb")
Fond_Du_Lac_Tribal_pdf = open("/Users/varshamadapoosi/Downloads/fond_du_lac.pdf", "rb")
red_lake_pdf = open("/Users/varshamadapoosi/Downloads/red_lake.pdf", "rb")
white_earth_pdf = open("/Users/varshamadapoosi/Downloads/white_earth.pdf", "rb")
lincoln_pdf = open("/Users/varshamadapoosi/Downloads/lincoln_university.pdf", "rb")
fort_peck_pdf = open("/Users/varshamadapoosi/Downloads/fort_peck_cc.pdf", "rb")
little_big_horn_pdf = open("/Users/varshamadapoosi/Downloads/little_big_horn_college.pdf", "rb")
Cankdeska_Cikana_pdf = open("/Users/varshamadapoosi/Downloads/2019_2022_CCCC_Catalog.pdf", 'rb')
Nueta_Hidatsa_Sahnish_pdf = open("/Users/varshamadapoosi/Downloads/Nueta Hidatsa Sahnish College.pdf", "rb")
Sitting_Bull_College_pdf = open("/Users/varshamadapoosi/Downloads/sitting_bull.pdf", "rb")
turtle_mountain_pdf = open("/Users/varshamadapoosi/Downloads/turtle_mountain.pdf", "rb")
united_tribes_pdf = open("/Users/varshamadapoosi/Downloads/united_tribes.pdf", "rb")
northern_marianas_pdf = open("/Users/varshamadapoosi/Downloads/norther_marianas.pdf", "rb")
pdfread = pypdf.PdfFileReader(northern_marianas_pdf)
pdfread

In [6]:
y = pdfread.getPage(3)
y.extractText().replace("\n", " ")

'2012 - 2013 CATALOG   NORTHERN MARIANAS COLLEGE     126   |  Page             required. English Placement Level: EN 093/094. Math Placement Level: MA 091.  (Offered   Fall  and Spring)     BI 103     Marine Biology            (4)   This course provides an introduction to the biology of the marine environment. Special  emphasis is placed on the marine environment of Micronesia and its importance to island  communities.  Laboratory exerc ises and field trips are designed to bring students into contact  with local marine organisms and their habitats.  Laboratory and field trips are required.  Ability  to swim is recommended but not required.  English Placement Level: EN 093/094. Math  Placemen t Level: MA 091.     BI 106      Agricultural Science            (4)   This course provides an overview of the biology of agriculture. This course examines the  interdisciplinary role functions and impact of animal and plant production on humans, on the  environment, and  society. Topics will include production fundamentals of food, fiber, and  medicinal plants; the production of food animals; integrated pest management ecology; political  and socioeconomic issues of agro - ecology; biotechnological advances in the discipline;  and  sustainable agriculture. Laboratory and field trips are required.  English Placement Level: EN  093/094.  Math Placement Level: MA 091.     BI 141      Plant Science              (4)   This course introduces students to the study of living plants to illustrate the fun damental  principles of plant ecology.  Topics will cover cellular organization, photosynthesis, respiration,  growth and development, reproduction, mineral nutrition, and water absorption.  Laboratory  and field trips are required.  English Placement Level:  EN 093/094.  Math Placement Level: MA  091.      BI 201     Natural History of the Mariana Islands      (4)   This is a natural history survey course covering the geology, ecology, and flora and fauna of  the Mariana Islands.  Laboratory and field trips are required.   As part of the field trips,  swimming or hiking may be required.  English Placement Level: EN 093/094. Math Placement  Level: MA 091.     BI 225      Basic Microbiology           (4)   This is a survey course covering the major groups of microorganisms in relation to thei r  classification, characteristics, and medical importance, and introduces students to related  topics in immunology and epidemiology. It is intended for students entering the fields of  professional health care, although other students may wish to enroll in  the course.  Laboratory   Level: EN 101.  Math Placement Level: MA 132.  (Offered Fall and Spring)       BI 251      Human Anatomy and Physiology I        (4)   This is the f irst part of a two - semester sequence covering human anatomy and physiology at  the biochemical, cellular, microscopic, tissue, and organ levels. In this course, all body systems  are presented, discussed, and integrated with one another. This course is desig ned for those  entering professional health care fields, although enrollment is open to all students. Laboratory  and field trips are required. Prerequisites: BI 101, CH 124. English Placement Level: EN 202.  Math Placement Level: MA 132.  (Offered Fall)     BI  252      Human Anatomy and Physiology II       (4)   '

In [11]:
#leech_Lake_pattern = "no"
#Lac_Courte_Oreilles_Ojibwa_pattern = "no"
#Aaniiih_Nakoda_pattern = ([a-zA-z ]+\s{1}\(\w+\)\s{5})?([a-zA-Z]+)\s([a-zA-z0-9]+\w?)\s([a-zA-z0-9\s]+\([0-9]\s?\)\s{3}
#Blackfeet_CC_pattern = ([a-zA-Z]+)\s{1}([0-9]+\s)\|\s{1}([a-aA-z ]+) #no dep name
#Southwest_Indian_polytechnic_pattern = ([a-zA-z ]+\s{2})?([a-zA-Z]+)\s([\d]+\w?)\s{1}([a-zA-z0-9\s]+\([0-9]\))
#Keweenaw_Bay_Ojibwa_pattern = \s{2}([a-zA-z\s\(\)]+\s{2})?([a-zA-Z0-9]+\s)([a-zA-z ]+)-
#Fond_Du_Lac_Tribal_pattern = "can't figire"
#red_lake_pattern = ([A-Z]+\s[0-9]+:)\s([a-zA-z ]+\s)([a-zA-z0-9 :]+Course Description) #might work need to test
#white_earth_pattern = ([A-Z\s\(]+\)\s{1})?([A-Z0-9 ]+:)+\s{2}([a-zA-z ]+)+ #only works for a couple need to test
#lincoln_pattern = \s([a-zA-z\s]+\sCourse Descriptions)?\s([A-Z]+\s[0-9]+)\s([a-zA-z ]+)
#Cankdeska_Cikana_pattern = "hard"
#Nueta_Hidatsa_Sahnish_pattern = (\s{5}[a-zA-z \(\)]+\s{3})?([a-zA-z0-9]*\s[0-9]+)\s([a-zA-z ]+)
#sitting_bull_college_pattern = (\s{5}[a-zA-z \(\)]+\s{3})?([0-9]{2,})\s{3}([A-Z -]+)
#turtle_mountain_pattern = (\s{5}[A-Z]+\s[0-9]+)\s([a-zA-z ]+)
#united tribes_pattern = ([A-Z]+\s[0-9]+)\s([A-Z ]+)
#northern_marianas_pattern = ([A-Z]+\s{3})?([A-Z]+\s[0-9]+)\s{3,}([a-zA-z ]+)

In [254]:
def get_data(csv_name, pdf_name, page_range, pattern, dep_group, abbrev_group, c_group, t_group,
            year, grad_status):
    """Takes in name of PDF in local folder and extracts data in given PAGE_RANGE 
    using regex expression PATTERN and given group numbers. YEAR is the catalog year.
    GRAD_STATUS is either None (if unknown), 'G', 'UG', or a number indicating at
    which number is the course graduate."""
    saved_dep_name = ""
    PDFfile = open(pdf_name, "rb")
    pdfread = pypdf.PdfFileReader(PDFfile)
    
    csv_writer = csv.writer(open(csv_name, 'w'))
    csv_writer.writerow(["Department Name", "Course Catalogue Number", "Course Name",
     "Course Description", "Graduate/Undergraduate", "Format", "Lab", 
     "Academic Catalogue Year"])
    FS_keys = ["agri", "food", "animal"]
    
    look_ahead = pattern + r'(.+?)(?=' + pattern + r')'
    
    dep_names = {}
    for i in np.arange(page_range[0], page_range[1]):
        page_text = pdfread.getPage(i).extractText().replace('\n', ' ')
        matches = re.findall(look_ahead, page_text)
           
        one = re.sub(look_ahead, '', page_text)

        last = re.search(pattern + r'(.+)', one)
        
    
        matches = matches + [(last.group(dep_group), last.group(abbrev_group), 
                    last.group(c_group), last.group(t_group), last.group(5))]
        

        for match in matches:  
            
            # Getting full department name
            if match[dep_group - 1] != '':
                dep_names[match[abbrev_group - 1]] = match[dep_group - 1]
            
            dep_name = dep_names.get(match[abbrev_group - 1])
            
            if dep_name != None:
                saved_dep_name = dep_name
                if len(dep_name) <2 :
                    dep_name = match[abbrev_group - 1] #tried this need to improve it 
            if dep_name == None:
                dep_name = saved_dep_name
            
                
            # Other groups
            course_num = match[abbrev_group - 1] + (match[c_group - 1][:3]) #added the abbrevation in front of number for those that don't have department name separate
            title = str(match[t_group - 1])
            desc = str(match[4]) # assuming description is group 5
            
          
            #Filtering
            for key in FS_keys:
                if (re.search(key, title, flags=re.IGNORECASE) or 
                    re.search(key, desc, flags=re.IGNORECASE)):
                    G_UG = grad_status
                    if grad_status:
                        if type(grad_status) == int:
                            G_UG = "UG"
                            if int(t.group(1)) >= grad_status:
                                G_UG = "G"
                    lab = False
                    if (re.search(r'Laboratory|Lab', title, flags=re.IGNORECASE) or 
                    re.search(r'Laboratory|Lab', desc, flags=re.IGNORECASE)):
                        lab = True
                    csv_writer.writerow([dep_name, course_num, title, desc, 
                                             "Undergraduate", None, "lab", year])
                                            # Leaving format blank for now

In [235]:
Saginaw_Chippewa_pattern = r'([A-Z ]+\s{3}\(\w+\)\s{5})?([a-zA-Z ]+)\s([a-zA-z0-9]+\w?)\s([a-zA-z0-9\s:]+\([0-9]\s?\))'
Saginaw_Chippewa_data = get_data('Saginaw_Chippewa.csv', "/Users/varshamadapoosi/Downloads/Saginaw Chippewa Tribal College.pdf", [29,38], Saginaw_Chippewa_pattern, 
         1, 2, 3, 4, '2019-2020', None)
pd.read_csv('Saginaw_Chippewa.csv')

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,BIOLOGY (Science),BIO216,Native American Plants and Medicines (3),This course is an introduction to the stu...,Undergraduate,NaN,lab,2019-2020
1,HUMANITIES (Humanities),NAS259,Anishinaabe Histor y : Beginning s to 1600...,(HUM) This course is explores the history o...,Undergraduate,NaN,lab,2019-2020
2,HUMANITIES (Humanities),N A S261,Survey of Native American History (3),(HUM) This course covers major governmental...,Undergraduate,NaN,lab,2019-2020

In [236]:
Aaniiih_Nakoda_pattern = r'([a-zA-z ]+\s{1}\(\w+\)\s{5})?([a-zA-Z]+)\s([a-zA-z0-9]+\w?)\s([a-zA-z0-9\s]+\([0-9]\s?\))\s{3}'
Aaniiih_Nakoda_data = get_data('Aaniiih_Nakoda.csv', "/Users/varshamadapoosi/Downloads/Aaniiih Nakoda College.pdf", [76,106], Aaniiih_Nakoda_pattern, 
         1, 2, 3, 4, '2019-2020', None)
pd.read_csv('Aaniiih_Nakoda.csv')

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,American Indian Studies (AIS),AIS120,Traditional Plants (3),Prerequisit e: None This course will descr...,Undergraduate,NaN,lab,2019-2020
1,American Indian Studies (AIS),BIOBL16,Principles of Living Systems Lab (1),Prerequisite: None Laboratory studies in ...,Undergraduate,NaN,lab,2019-2020
2,American Indian Studies (AIS),BIOH,210 General Clinical Nutrition (3),"Prerequisite: BIOB 160/L160, CHMY 121/L121 o...",Undergraduate,NaN,lab,2019-2020
3,American Indian Studies (AIS),BIOO120,Intro to Ethnobotany (3),Prerequisite: None This course will descri...,Undergraduate,NaN,lab,2019-2020
4,American Indian Studies (AIS),BGEN110,American Indian Business Leadership (1),Prerequisite: None Students will engage i...,Undergraduate,NaN,lab,2019-2020
5,Environmental Science (ENSC),ENSC291,Introduction to Global Climate Change (3),Prerequisite: Environmental Science C...,Undergraduate,NaN,lab,2019-2020
6,Aaniiih Nakoda College Geography (G...,HLPE170,Nurse Aide (5),Prerequisite: None This course provides cl...,Undergraduate,NaN,lab,2019-2020
7,Aaniiih Nakoda College Geography (G...,GlobalPos,Systems [GPS] (3),Prerequisite: Instructor Approval This cla...,Undergraduate,NaN,lab,2019-2020
8,Aaniiih Nakoda College Geography (G...,NUTR221,Basic Human Nutrition (3),Prerequisite: BIOB 160/L160 or Instructor Ap...,Undergraduate,NaN,lab,2019-2020

In [237]:
Southwest_Indian_polytechnic_pattern = r'(\s{2}[A-Z ]+)?\s{2}([A-Z]+\s{1,2})([0-9]+)\s([a-zA-z ]+\()'
Saginaw_Chippewa_data = get_data('Southwest_Indian_polytechnic.csv', "/Users/varshamadapoosi/Downloads/SIPI 2017-2018 Catalog Final.pdf", [60,85], Southwest_Indian_polytechnic_pattern, 
         1, 2, 3, 4, '2017-2018', None)
pd.read_csv('Southwest_Indian_polytechnic.csv') #last doesnt work(cant find matches--adds DESCRIPTIONS)

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,AGRICULTURE,AGTC 202,Introduction to Soil Science (,"3) Prerequisites: CHEM 121, CHEM 121 L; Co-...",Undergraduate,NaN,lab,2019-2020
1,AGRICULTURE,AGTC 280,Agricultural Internship (,3) Prerequisites: Second year standing Thi...,Undergraduate,NaN,lab,2019-2020
2,AGRICULTURE,AGTC 290,Special Topics in Agriculture (,1 -4) Prerequisites: Second year standing Th...,Undergraduate,NaN,lab,2019-2020
3,BIOLOGY,BIOL 220,Genera l Zoology (,"3) Prerequisites: ENGL 100, MATH 100, BIOL ...",Undergraduate,NaN,lab,2019-2020
4,CULINARY ARTS,CULN 101,Safety and Sanitation (,2) Prerequisite: Enrolled in the Culinary Ar...,Undergraduate,NaN,lab,2019-2020
5,CULINARY ARTS,CULN 102,Skills I Lecture (,1) Prerequisite: Enrolled in the Culinary A...,Undergraduate,NaN,lab,2019-2020
6,CULINARY ARTS,CULN 102,L Skills I Lab Basic Food Preparation (,3) Prerequisite: Enrolled in the Culinary A...,Undergraduate,NaN,lab,2019-2020
7,CULINARY ARTS,CULN 209,International Cuisine (,2) Prerequisite : CULN 207 American Regional ...,Undergraduate,NaN,lab,2019-2020
8,CULINARY ARTS,CULN 211,Student Internship (,1) (250 hours) Prerequisite : CUL N 208L Ad...,Undergraduate,NaN,lab,2019-2020
9,ENVIRONMENTAL SCIENCE,ENVS 122,Environmental Science II (,3) Prerequisite: ENVS 121/L Provides a conti...,Undergraduate,NaN,lab,2019-2020
10,PHILOSOPHY,PHIL 210,Ethics (,3) Prerequisites: This course invites a dia...,Undergraduate,NaN,lab,2019-2020

In [243]:
Keweenaw_Bay_Ojibwa_pattern = r'(\s{5}[a-zA-z\s\(\)]+\s{2})?([A-Z]+)([0-9]+)([a-zA-z ]+-)'
Keweenaw_Bay_Ojibwa_data = get_data('Keweenaw_Bay_Ojibwa.csv', "/Users/varshamadapoosi/Downloads/2018-2020-KBOCC-Catalog.pdf", [58,71], Keweenaw_Bay_Ojibwa_pattern, 
         1, 2, 3, 4, '2018-2020', None)    
pd.read_csv('Keweenaw_Bay_Ojibwa.csv')

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,BIOLOGY (BI),BI203,Wildlife Biology and Management -,"4 (3 lecture, 3 lab) Introduction to the...",Undergraduate,NaN,lab,2019-2020
1,BIOLOGY (BI),BI206,Principles of Ecology -,"4 (3 lecture, 3 lab) Examination of the ...",Undergraduate,NaN,lab,2019-2020
2,ENVIRONMENTAL SCIENCE (ES),ES158,Human Geography -,4 Examin ation of world geographic condit...,Undergraduate,NaN,lab,2019-2020
3,FOODS AND NUTRITION (FN),FN101,Basic Cooking Methods -,2 (1 lecture 2 lab) This is a hands - on...,Undergraduate,NaN,lab,2019-2020
4,FOODS AND NUTRITION (FN),FN201,Local and Native Cuisine -,"2 (1 lecture 2 lab) Local, Organic, Seas...",Undergraduate,NaN,lab,2019-2020
5,,FN202,Essential Elements of Restaura nt Management -,3 Focuses on the leadership and manageme...,Undergraduate,NaN,lab,2019-2020

In [250]:
red_lake_pattern = r'([0-9]+)?([A-Z]+)\s([0-9]+):([a-zA-z ]+Credits)'
red_lake_data = get_data('red_lake.csv', "/Users/varshamadapoosi/Downloads/red_lake.pdf", [58,71], red_lake_pattern, 
         1, 2, 3, 4, '2019-2020', None)    #'NoneType' object has no attribute 'group'
pd.read_csv('red_lake.csv')

AttributeError: 'NoneType' object has no attribute 'group'

In [255]:
white_earth_pattern = r'([A-Z\s\&(]+\)\s{3})?([A-Z]+)\s([0-9]+):\s([a-zA-z \/]+\s{2})' 
white_earth_data = get_data('white_earth.csv', "/Users/varshamadapoosi/Downloads/white_earth.pdf", [13,21], white_earth_pattern, 
         1, 2, 3, 4, '2018-2019', None)    
pd.read_csv('white_earth.csv')

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,BIOLOGY (BIOL),BIOL100,General Biology w /Lab,- 4 credits A general overview of the pri...,Undergraduate,NaN,lab,2019-2020

In [265]:
lincoln_pattern = r'(\s{2}[a-zA-z\s]+\sCourse Descriptions\s{2})?([A-Z]+)\s([0-9]+)\s([a-zA-z ]+)'
lincoln_data = get_data('lincoln.csv', "/Users/varshamadapoosi/Downloads/lincoln_university.pdf", [78,314], lincoln_pattern, 
         1, 2, 3, 4, '2019-2020', None)    #'NoneType' object has no attribute 'group' -->
pd.read_csv('lincoln.csv')

AttributeError: 'NoneType' object has no attribute 'group'

In [186]:
Nueta_Hidatsa_Sahnish_pattern = r'(\s{5}[a-zA-z ]+\([ A-Z]+\))?\s{1,}([A-Z]+)?\s([0-9]{2,})([a-zA-Z &]+)'
nueta_hidatsa_sahnish_data = get_data('nueta_hidatsa_sahnish.csv', "/Users/varshamadapoosi/Downloads/Nueta Hidatsa Sahnish College.pdf", [76,109], Nueta_Hidatsa_Sahnish_pattern, 
         1, 2, 3, 4, '2018-2019', None)   
pd.read_csv('nueta_hidatsa_sahnish.csv')

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,Addi ction Studies ( ADS ),223,Alcohol and Drug Treatment Continuum Fall of,2019 3 CREDITS This course will emph...,Undergraduate,NaN,lab,2019-2020
1,Biology ( BIO ),151,General Biology II,4 CREDITS A continuation of Biology I wi...,Undergraduate,NaN,lab,2019-2020
2,Biology ( BIO ),81,Overview o f the principles governing the...,", animals, and environments. Emphasis is on e...",Undergraduate,NaN,lab,2019-2020
3,Biology ( BIO ),331,Soil Ecology,3 CREDITS This course engages students wit...,Undergraduate,NaN,lab,2019-2020
4,Biology ( BIO ),331,Soil Ecology,3 CREDITS This course engages students wit...,Undergraduate,NaN,lab,2019-2020
5,Biology ( BIO ),421,Environmental Toxicology,"3 CREDITS In this course, students will ...",Undergraduate,NaN,lab,2019-2020
6,Biology ( BIO ),433,Wildlife Ecology,3 CREDITS This course will examine the the...,Undergraduate,NaN,lab,2019-2020
7,Biology ( BIO ),444,Grassland Ecology,"3 CRE DITS This course covers the plant, a...",Undergraduate,NaN,lab,2019-2020
8,Horticulture ( HORT ),111,Organic Gardeni ng I,(Summer Session Only) 3 CREDITS ...,Undergraduate,NaN,lab,2019-2020
9,Horticulture ( HORT ),112,O rganic Gardenin g II,(Summer Session Only) 3 CREDITS ...,Undergraduate,NaN,lab,2019-2020
10,History ( HIST ),210,Introduction to Ethnopedology,3 CREDITS A hybrid discipline that e nco...,Undergraduate,NaN,lab,2019-2020
11,History ( HIST ),220,Reservation Economics,3 CREDITS The study of comparative econo...,Undergraduate,NaN,lab,2019-2020
12,History ( HIST ),225,Traditional Gardening and Foods,3 CREDITS This course is designed to re - i...,Undergraduate,NaN,lab,2019-2020
13,History ( HIST ),402,Agricultural & Natural Resource Management in...,. 3 CREDITS This class will concent...,Undergraduate,NaN,lab,2019-2020
14,Public Health ( PH ),111,Interdisciplinary Approaches to Public Heal...,1 CREDIT This course introduce s undergrad...,Undergraduate,NaN,lab,2019-2020
15,Public Health ( PH ),111,Interdisciplinary Approaches to Public Heal...,1 CREDIT This course introduce s undergrad...,Undergraduate,NaN,lab,2019-2020
16,Social Work (SWK),331,Soil Ecology,3 CREDITS This course engages students wit...,Undergraduate,NaN,lab,2019-2020
17,Social Work (SWK),331,Soil Ecology,3 CREDITS This course engages students wit...,Undergraduate,NaN,lab,2019-2020

In [190]:
sitting_bull_college_pattern = r'(\s{5}[a-zA-z \(\)]+\s{3})?([A-Z]+)?([0-9]{2,})\s{3}([A-Z -]+)'
sitting_bull_data = get_data('sitting_bull.csv', "/Users/varshamadapoosi/Downloads/sitting_bull.pdf", [188,259], sitting_bull_college_pattern, 
         1, 2, 3, 4, '2018-2020', None)    #need to get rid of all the ..... in the course description manually --should be fairly easy
pd.read_csv('sitting_bull.csv')

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,DIVISION OF AGRICULTURE AGRICULTURAL ...,141,INTRODUCTION TO AGRI - BUSINESS MANAGEMENT,................................ ................,Undergraduate,NaN,lab,2019-2020
1,DIVISION OF AGRICULTURE AGRICULTURAL ...,297,AGRICULTURE INTERNSHIP,................................ ................,Undergraduate,NaN,lab,2019-2020
2,DIVISION OF AGRICULTURE AGRICULTURAL ...,299,AGRICULTURAL ECONOMICS SPECIAL TOPICS,................................ ................,Undergraduate,NaN,lab,2019-2020
3,ANIMAL AN D RANGE SCIENCE (ARSC),114,INTRODUCTION TO ANIMAL SCIENCE,................................ ................,Undergraduate,NaN,lab,2019-2020
4,ANIMAL AN D RANGE SCIENCE (ARSC),220,LIVESTOCK PRODUCTION,................................ ................,Undergraduate,NaN,lab,2019-2020
5,ANIMAL AN D RANGE SCIENCE (ARSC),299,ANIMAL AND RANGE SCIENCE SPECIAL TOPICS,................................ ................,Undergraduate,NaN,lab,2019-2020
6,COMPUTER SCIENCE (CSCI),132,COMM ERICIAL,& AGRICULTURAL WIRING .......................,Undergraduate,NaN,lab,2019-2020
7,,200,NUTRITION,................................ ................,Undergraduate,NaN,lab,2019-2020
8,SCIENCES BIOLOGY (BIOL),150,GENERAL BIOLOGY I,................................ ................,Undergraduate,NaN,lab,2019-2020
9,SCIENCES BIOLOGY (BIOL),70,ZOOLOGY,................................ ................,Undergraduate,NaN,lab,2019-2020
10,SCIENCES BIOLOGY (BIOL),431,GRASSLAND ECOLOGY,................................ ................,Undergraduate,NaN,lab,2019-2020
11,ENVIRONMENTAL SCIENCE (ENS),520,ADVANCED TECHNIQUES IN GIS,................................ ................,Undergraduate,NaN,lab,2019-2020
12,,554,GRASSLAND ECOLOGY,................................ ................,Undergraduate,NaN,lab,2019-2020
13,,556,ECOLOGY OF INVASIVE SPECIES,................................ ................,Undergraduate,NaN,lab,2019-2020
14,,558,RESTORATION ECOLOGY,................................ ................,Undergraduate,NaN,lab,2019-2020
15,GEOLOGY (GEOL),122,INTENSIVE OCHETHI SAKOWIN FOR BEGINNERS II,................................ ................,Undergraduate,NaN,lab,2019-2020
16,GEOLOGY (GEOL),123,INTENSIVE OCHETHI SAKOWIN FOR BEGINNERS III,................................ ................,Undergraduate,NaN,lab,2019-2020
17,GEOLOGY (GEOL),101,OCHETHI SAKOWIN LANGUAGE FOR BEGINNERS,................................ ................,Undergraduate,NaN,lab,2019-2020
18,GEOLOGY (GEOL),101,OCHETHI SAKOWIN LANGUAGE FOR BEGINNERS,................................ ................,Undergraduate,NaN,lab,2019-2020

In [217]:
turtle_mountain_pattern = r'([A-Z])?(\s{5}[A-Z]+)\s([0-9]+)\s([a-zA-z ]+)'
turtle_mountain_data = get_data('turtle_mountain.csv', "/Users/varshamadapoosi/Downloads/turtle_mountain.pdf", [158,227], turtle_mountain_pattern, 
         1, 2, 3, 4, '2019-2020', None)    
pd.read_csv('turtle_mountain.csv')

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,NaN,BIOL170,General Zoology I,/Lab 4 Credits A survey of the animal king...,Undergraduate,NaN,lab,2019-2020
1,I,GEOL106,The Earth Through Time,/Lab 4 Credits he evolution of plant and ...,Undergraduate,NaN,lab,2019-2020
2,I,NRM190,Turtle Mountain Systems I,3 Credits The course provides hand - on inst...,Undergraduate,NaN,lab,2019-2020
3,I,NRM200,Turtle Mountain Systems II,3 Credits The course provides hand - on in...,Undergraduate,NaN,lab,2019-2020
4,I,NRM210,Capstone Project,3 Credits The purpose of the Capstone Projec...,Undergraduate,NaN,lab,2019-2020

In [215]:
united_tribes_pattern = r'([A-Z])?\s([A-Z]+)\s([0-9]+)\s([A-Z\s]{5,})'
united_tribes_data = get_data('united_tribes.csv', "/Users/varshamadapoosi/Downloads/united_tribes.pdf", [99,136], united_tribes_pattern, 
         1, 2, 3, 4, '2019-2020', None)    
pd.read_csv('united_tribes.csv')

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,DESCRIPTIONSAAGR,DESCRIPTIONSAAGR121,INTRODUCTION TO SUSTAINABLE AGRICULTURE AND ...,(3 CREDITS)A broad interdisciplinary introduct...,Undergraduate,NaN,lab,2019-2020
1,DESCRIPTIONSAAGR,DESCRIPTIONSAAGR121,INTRODUCTION TO SUSTAINABLE AGRICULTURE AND ...,(3 CREDITS)A broad interdisciplinary introduct...,Undergraduate,NaN,lab,2019-2020
2,E,AGR221,SUSTAINABLE COMMUNITY FOOD SYSTEMS,(3 CREDITS) application for the course ma...,Undergraduate,NaN,lab,2019-2020
3,AGR,AGR297,CAMPUS FARM INTERNSHIP,"(1 CREDIT) technical food production, and the...",Undergraduate,NaN,lab,2019-2020
4,B,BIO340,ENVIRONMENTAL VIROLOGY,(3 CREDITS)This course will cover the principl...,Undergraduate,NaN,lab,2019-2020
5,B,BIO402,ANIMAL BEHAVIOR,(3 CREDITS) situations. A focus will be on e...,Undergraduate,NaN,lab,2019-2020
6,E,NUT100,INTRODUCTION TO NUTRITION AND FOODSERVICE,(2 CREDITS)This course is an introductory over...,Undergraduate,NaN,lab,2019-2020
7,E,NUT105,MANAGING FOOD PROTECTION,(3 CREDITS)The course focuses on basic food sa...,Undergraduate,NaN,lab,2019-2020
8,E,NUT210,QUANTITY FOODS,(5 CREDITS) Quantity food preparation will f...,Undergraduate,NaN,lab,2019-2020
9,E,NUT240,FUNDAMENTALS OF NUTRITION,"(3 CREDITS) review nutritional guidelines, fo...",Undergraduate,NaN,lab,2019-2020
10,E,NUT245,MENU PLANNING,(3 CREDITS)This course focuses on the fundamen...,Undergraduate,NaN,lab,2019-2020
11,E,NUT251,MANAGING FOODSERVICE OPERATIONS,(4 CREDITS)This course introduces basic foodse...,Undergraduate,NaN,lab,2019-2020
12,E,NUT297,FOODSERVICE INTERNSHIP,(3 CREDITS) or off reservation communit...,Undergraduate,NaN,lab,2019-2020

In [220]:
northern_marianas_pattern = r'([A-Z]+\s{3})?([A-Z]+)\s([0-9]+)\s{3,}([a-zA-z ]+)'
northern_marianas_data = get_data('northern_marianas.csv', "/Users/varshamadapoosi/Downloads/norther_marianas.pdf", [0,40], northern_marianas_pattern, 
         1, 2, 3, 4, '2012-2013', None)    
pd.read_csv('northern_marianas.csv')

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,SCIENCE,BI106,Agricultural Science,(4) This course provides an overview of the ...,Undergraduate,NaN,lab,2019-2020
1,SCIENCE,BI106,Agricultural Science,(4) This course provides an overview of the ...,Undergraduate,NaN,lab,2019-2020
2,SCIENCE,BI106,Agricultural Science,(4) This course provides an overview of the ...,Undergraduate,NaN,lab,2019-2020
3,HEALTH,HE230,Nutrition and H ealth,(3) This course covers the basic elements an...,Undergraduate,NaN,lab,2019-2020
4,HISTORY,HI121,History of World Civilizations I,(3) This course is the first half of a compr...,Undergraduate,NaN,lab,2019-2020
5,MUSIC,NR295,Natural Resources Management Semina r,(1) This course presents seminar presentatio...,Undergraduate,NaN,lab,2019-2020
6,MUSIC,NR298,Natural Resources Management Internship,(4) This is a required course for majors des...,Undergraduate,NaN,lab,2019-2020

In [273]:
fond_du_lac_pattern = r'([A-Z \(\)]+\s{2})?(\.\s{2,}[A-Z]+)\s([0-9*]+)\s([0-9- a-zA-z]+\s{2})'
fond_du_lac_data = get_data('fond_du_lac.csv', "/Users/varshamadapoosi/Downloads/fond_du_lac.pdf", [1,39], fond_du_lac_pattern, 
         1, 2, 3, 4, '2019-2020', None)    
pd.read_csv('fond_du_lac.csv')

AttributeError: 'NoneType' object has no attribute 'group'

In [282]:
Cankdeska_Cikana_pattern = r'([a-zA-z ]+\([A-Z]+\))?([A-Z]+)\s([0-9]+)\sŒ\s([.a-zA-z- 0-9]+)'
Cankdeska_Cikana_data = get_data('Cankdeska_Cikana.csv', "/Users/varshamadapoosi/Downloads/2019_2022_CCCC_Catalog.pdf", [50,60], Cankdeska_Cikana_pattern, 
         1, 2, 3, 4, '2019-2020', None)    
pd.read_csv('Cankdeska_Cikana.csv')

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,Academic Skills Courses (ASC),HIST103,U.S. HISTORY TO 1877,"(3 credits).An economic, intellectual, politic...",Undergraduate,NaN,lab,2019-2020

In [288]:
blackfeet_pattern = r'([a-z]+)?([a-zA-Z]+)\s{1}([0-9]+\s)\|\s{1}([a-aA-z ]+)' #no dep name
blackfeet_data = get_data('blackfeet.csv', "/Users/varshamadapoosi/Downloads/Blackfeet Community College.pdf", [91,112], blackfeet_pattern, 
         1, 2, 3, 4, '2019-2020', None)    
pd.read_csv('blackfeet.csv')

,Department Name,Course Catalogue Number,Course Name,Course Description,Graduate/Undergraduate,Format,Lab,Academic Catalogue Year
0,NaN,BIOB170,Principles of Biological Diversity,| 3 Credits Co-Requisite: BIOB 171 Examinatio...,Undergraduate,NaN,lab,2019-2020
1,NaN,BMGT190,Resources in Agriculture,| 3 Credits Course covers a series of workshop...,Undergraduate,NaN,lab,2019-2020
2,NaN,HEE223,Personal Community School and Health Issues,| 3 Credits This course will introduce health...,Undergraduate,NaN,lab,2019-2020
3,NaN,NAT105,Introduction to Natural Resources,| 3 Credits This course is designed to provide...,Undergraduate,NaN,lab,2019-2020
4,NaN,NUTR221,Basic Human Nutrition,| 3 Credits This course covers the basic conce...,Undergraduate,NaN,lab,2019-2020
5,NaN,PKNI120,Piikani Ecological Knowledge,| 3 Credits This course provides outdoor and ...,Undergraduate,NaN,lab,2019-2020
6,NaN,PSYX100,Introduction to Psychology,| 3 Credits This course is intended as an int...,Undergraduate,NaN,lab,2019-2020
7,NaN,SCI290,Special Topics in Science,| Variable Credits This is an independent stud...,Undergraduate,NaN,lab,2019-2020

In [ ]:
blackfeet_pattern = r'([a-z]+)?([a-zA-Z]+)\s{1}([0-9]+\s)\|\s{1}([a-aA-z ]+)' #no dep name
blackfeet_data = get_data('blackfeet.csv', "/Users/varshamadapoosi/Downloads/Blackfeet Community College.pdf", [91,112], blackfeet_pattern, 
         1, 2, 3, 4, '2019-2020', None)    
pd.read_csv('blackfeet.csv')